title: Improving Neuroimaging Data for Sharing
email: robert.oostenveld@donders.ru.nl
description: INDoS COST Action
baseurl: ""
url: "https://www.indos-costaction.eu"
logo: "/assets/images/logo/INDoS _ logo left.png"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
header_pages:
  - index.md
  - collaborators.md
  - workgroups.md
  - contact.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - STRUCTURE.md
  - LICENSE.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"